server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.104.249.198:3306/ai_chat?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: Zz123.123..
  ai:
    model:
      chat: deepseek
    deepseek:
      base-url: https://api.deepseek.com
      api-key: sk-aa9fa9ebd95e450da8207dac19dfe00f
      chat:
        model: deepseek-v4-pro
        temperature: 0.8
    mcp:
      client:
        enabled: false
tavily:
  search-url: https://api.tavily.com/search
  mcp-url: https://mcp.tavily.com/mcp/
  api-key: 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
  max-results: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: cn.cosx.chat.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
